# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDesgaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('tempo_inicio', models.TimeField()),
                ('tempo_fim', models.TimeField()),
                ('peso', models.DecimalField(decimal_places=5, max_digits=12)),
            ],
        ),
    ]
