# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancadaweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Person',
        ),
    ]
