# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancadaweb', '0002_auto_20160516_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Supercalifragilistic',
            field=models.TextField(default=b'SupercalifragilisticSupercalifragilisticSupercalifragilistic', max_length=100, verbose_name=b'Supercalifragilistic'),
        ),
    ]
