# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancadaweb', '0003_person_supercalifragilistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDesgaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_inicio', models.TimeField()),
                ('tempo_fim', models.TimeField()),
                ('peso', models.DecimalField(decimal_places=5, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
